import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="overflow-hidden">
        <div>
          <h1 className="w-full flex items-center justify-center bg-red-400 font-bold text-2xl">
            Em construção!
          </h1>
        </div>
        {children}
      </body>
    </html>
  );
}
